on:
  push
#schedule:
#  - cron: "0 22 * * *"
jobs:
  daliyNHK:
    name: build&update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: denolib/setup-deno@v1.3.0
      - id: compare-date
        run: deno run -A main.ts
      - run: |
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git add .
          git commit -m "Vue blog regularly update" -a
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
